Completed steps B1-B3 for basic workflow - > tedummyapp@1.0.0 workflows.prod /Users/abrinckman/dev/TEDummyApp > NODE_ENV=prod ./node_modules/mocha/bin/mocha
  Basic Flow (steps B1 - B3)
    #(B1) Get the identity of a user
      ✓ should find and return user by Id (264ms)
      ✓ should confirm identity of the user
    #(B2) Determine if user belongs to a choice or non-choice condition
      ✓ should belong to condition 'bard'
      ✓ should not belong to a 'choice' condition
    #(B3) Notify T&E system of user activity
      ✓ should successfully set last active
      ✓ should successfully save user activity (313ms)

  6 passing (595ms) or
> tedummyapp@1.0.0 workflows.dev /Users/abrinckman/dev/TEDummyApp
> NODE_ENV=dev ./node_modules/mocha/bin/mocha

  Basic Flow (steps B1 - B3)
    #(B1) Get the identity of a user
      1) should find and return user by Id
      2) should confirm identity of the user
    #(B2) Determine if user belongs to a choice or non-choice condition
      3) should belong to condition 'bard'
      4) should not belong to a 'choice' condition
    #(B3) Notify T&E system of user activity
      5) should successfully set last active
      6) should successfully save user activity

  0 passing (305ms)
  6 failing

  1) Basic Flow (steps B1 - B3)
       #(B1) Get the identity of a user
         should find and return user by Id:
     StatusCodeError: 404 - "{\"message\":\"Tue Nov 21 01:05:13 GMT 2017: User profile [5a0e603dc9e77c000cefd8aa] does not exist!\"}"
      at new StatusCodeError (node_modules/request-promise-core/lib/errors.js:32:15)
      at Request.plumbing.callback (node_modules/request-promise-core/lib/plumbing.js:104:33)
      at Request.RP$callback [as _callback] (node_modules/request-promise-core/lib/plumbing.js:46:31)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:1059:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Basic Flow (steps B1 - B3)
       #(B1) Get the identity of a user
         should confirm identity of the user:
     TypeError: Cannot read property 'get' of undefined
      at Context.<anonymous> (test/basic-flow.js:27:31)

  3) Basic Flow (steps B1 - B3)
       #(B2) Determine if user belongs to a choice or non-choice condition
         should belong to condition 'bard':
     TypeError: Cannot read property 'get' of undefined
      at Context.<anonymous> (test/basic-flow.js:37:29)

  4) Basic Flow (steps B1 - B3)
       #(B2) Determine if user belongs to a choice or non-choice condition
         should not belong to a 'choice' condition:
     TypeError: Cannot read property 'get' of undefined
      at Context.<anonymous> (test/basic-flow.js:41:32)

  5) Basic Flow (steps B1 - B3)
       #(B3) Notify T&E system of user activity
         should successfully set last active:
     TypeError: Cannot read property 'get' of undefined
      at Context.<anonymous> (test/basic-flow.js:50:37)

  6) Basic Flow (steps B1 - B3)
       #(B3) Notify T&E system of user activity
         should successfully save user activity:
     TypeError: Cannot read property 'get' of undefined
      at Context.<anonymous> (test/basic-flow.js:59:37)